### ISSUE TITLE
Check cookie site wide

### ISSUE THREAD

**Issue by crimsonpixel** [d0n601/drinkingAge#1]
I've used this script which works great as a gateway, however, if you know the url of a specfic web page within the site it would seem you can simply by pass it and the cookie isn't checked to see if you are of the correct age.  If the cookie states you are underage would it not be best to redirect to gateway page again.

Unless I've missed something....

**Comment by d0n601** [comment]
The bouncer.js and it's initial settings must be included on each page you wish to include the gateway on.

So if you're working in Wordpress you would initialize the plugin in your theme's footer.php.

**Comment by crimsonpixel** [comment]
Excellent - got that.  And I see you've added the deny_timeout to the config :)

One small error that I discovered is that if you simply click Enter without selecting any values you are deemed of age!  I amended this so that the year is the current year rather than -1.

One last question - when verification is successful can a user be directed to the home page of the site to start with so that even if they've tried to access via another URL they will always start from the home page

**Comment by crimsonpixel** [comment]
Also the cookie doesn't appear to be persistent as you can return to the age gateway and then enter your date of birth so that you are of age to drink and it will subsequently let you in....

**Comment by d0n601** [comment]
Thank you for catching that bug with the default values. I've updated the default year in commit [cf173be](https://github.com/d0n601/drinkingAge/commit/cf173bed739d99d85338da58348c523609458e26)

If you wish to have the script redirect to your homepage each time, rather than reloading the current page, you'll want to change line 69 within the submitAge function.
Modify `window.location.reload();` to become `window.location="http://yourhomepage.com";` 

The script does not create a cookie unless the user is found to be of valid drinking age for their region. I've designed it like this because I intended users who incorrectly entered their age, to have an opportunity to enter their age again to access the site. If a persistent cookie was created to redirect users who entered an insufficient age, users who entered an incorrect age on their first attempt would be forced to clear their browser's cookies and try once more, which I feel would be too great an impact on a site's usability.
